import { ACCESSORIES, SERVICES } from "./catalog";
import { minutesAgo, todayISO } from "./format";
import { segmentsFor } from "./process";
import type { AppState, Customer, Job, Technician } from "./types";

const customers: Customer[] = [
  {
    id: "c-demo",
    name: "Demo Müşteri",
    phone: "05551234567",
    plate: "06 ELT 01",
    vehicle: "2021 BMW 5.20i",
  },
  {
    id: "c-ayse",
    name: "Ayşe Kaya",
    phone: "05321220011",
    plate: "06 AYK 142",
    vehicle: "2019 Renault Megane",
  },
  {
    id: "c-cem",
    name: "Cem Yıldız",
    phone: "05423334455",
    plate: "06 CM 908",
    vehicle: "2022 Toyota Corolla",
  },
  {
    id: "c-burcu",
    name: "Burcu Şen",
    phone: "05076667788",
    plate: "06 BRC 77",
    vehicle: "2018 BMW 3.20",
  },
  {
    id: "c-oguz",
    name: "Oğuz Demir",
    phone: "05309876543",
    plate: "06 OGZ 330",
    vehicle: "2020 Ford Transit",
  },
];

const technicians: Technician[] = [
  { id: "t-mehmet", name: "Mehmet Usta", role: "Yıkama / kurutma", load: 3, shift: "08:30–17:00" },
  { id: "t-deniz", name: "Deniz Karaca", role: "Detailing", load: 2, shift: "09:00–18:00" },
  { id: "t-ali", name: "Ali Koç", role: "Lastik & balans", load: 2, shift: "08:30–18:30" },
  { id: "t-burak", name: "Burak Yol", role: "Yol yardım", load: 1, shift: "Sahada 24/7 nöbet" },
  { id: "t-elif", name: "Elif Aksoy", role: "Karşılama / kasa", load: 1, shift: "08:30–20:00" },
];

function shopJob(partial: Omit<Job, "segments" | "currentSegmentIndex" | "notifiedSegmentIndex"> & Partial<Pick<Job, "segments" | "currentSegmentIndex" | "notifiedSegmentIndex">>): Job {
  const segments = partial.segments ?? segmentsFor(partial.serviceId);
  return {
    currentSegmentIndex: partial.startedAt ? 0 : -1,
    notifiedSegmentIndex: partial.startedAt ? 0 : -1,
    ...partial,
    segments,
  };
}

export function buildSeed(): AppState {
  const today = todayISO();
  const ic = SERVICES.find((s) => s.id === "ic-dis-yikama")!;
  const dis = SERVICES.find((s) => s.id === "dis-yikama")!;
  const det = SERVICES.find((s) => s.id === "detayli-ic")!;
  const lastik = SERVICES.find((s) => s.id === "lastik-degisim")!;

  return {
    session: { role: "guest", name: "Misafir" },
    customers,
    technicians,
    jobs: [
      shopJob({
        id: "IS-1042",
        kind: "yikama",
        customerId: "c-ayse",
        customerName: "Ayşe Kaya",
        phone: "05321220011",
        plate: "06 AYK 142",
        vehicle: "2019 Renault Megane",
        serviceId: ic.id,
        serviceName: ic.name,
        notes: "Çocuk koltuğu var, hayvan tüyü yok.",
        estimate: 650,
        status: "yikamada",
        technicianId: "t-mehmet",
        startedAt: minutesAgo(12),
        currentSegmentIndex: 1,
        notifiedSegmentIndex: 1,
        createdAt: minutesAgo(40),
        updatedAt: minutesAgo(12),
        timeline: [
          { at: minutesAgo(40), status: "giris-bekleniyor", note: "Randevu alındı. Süreç giriş onayını bekliyor." },
          { at: minutesAgo(12), status: "yikamada", note: "Giriş onaylandı — sayaç başladı." },
        ],
      }),
      shopJob({
        id: "IS-1043",
        kind: "yikama",
        customerId: "c-cem",
        customerName: "Cem Yıldız",
        phone: "05423334455",
        plate: "06 CM 908",
        vehicle: "2022 Toyota Corolla",
        serviceId: dis.id,
        serviceName: dis.name,
        notes: "Sadece dış, acelem var.",
        estimate: 350,
        status: "giris-bekleniyor",
        technicianId: "t-mehmet",
        createdAt: minutesAgo(18),
        updatedAt: minutesAgo(18),
        timeline: [{ at: minutesAgo(18), status: "giris-bekleniyor", note: "Walk-in kayıt. Araç girişi henüz onaylanmadı." }],
      }),
      shopJob({
        id: "IS-1038",
        kind: "detailing",
        customerId: "c-burcu",
        customerName: "Burcu Şen",
        phone: "05076667788",
        plate: "06 BRC 77",
        vehicle: "2018 BMW 3.20",
        serviceId: det.id,
        serviceName: det.name,
        notes: "Deri koltuk bakım kremi uygulansın.",
        estimate: 2200,
        status: "yikamada",
        technicianId: "t-deniz",
        startedAt: minutesAgo(100),
        currentSegmentIndex: 1,
        notifiedSegmentIndex: 1,
        createdAt: minutesAgo(180),
        updatedAt: minutesAgo(100),
        timeline: [
          { at: minutesAgo(180), status: "giris-bekleniyor", note: "Randevulu kayıt." },
          { at: minutesAgo(100), status: "yikamada", note: "Giriş onaylandı — iç detailing sayacı." },
        ],
      }),
      shopJob({
        id: "IS-1031",
        kind: "lastik",
        customerId: "c-oguz",
        customerName: "Oğuz Demir",
        phone: "05309876543",
        plate: "06 OGZ 330",
        vehicle: "2020 Ford Transit",
        serviceId: lastik.id,
        serviceName: lastik.name,
        notes: "Ön iki lastik 215/75 R16C.",
        estimate: 4800,
        status: "teslim",
        technicianId: "t-ali",
        startedAt: minutesAgo(240),
        currentSegmentIndex: 3,
        notifiedSegmentIndex: 3,
        createdAt: minutesAgo(240),
        updatedAt: minutesAgo(50),
        timeline: [
          { at: minutesAgo(240), status: "giris-bekleniyor", note: "Lastikler kasadan çıktı." },
          { at: minutesAgo(200), status: "yikamada", note: "Giriş onaylandı." },
          { at: minutesAgo(50), status: "teslim", note: "Segmentler tamam, teslim." },
        ],
      }),
      shopJob({
        id: "IS-1044",
        kind: "yikama",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        serviceId: ic.id,
        serviceName: ic.name,
        appointmentId: "RDV-221",
        notes: "Demo — randevu saati geldi ama süreç başlamadı.",
        estimate: 650,
        status: "giris-bekleniyor",
        technicianId: "t-mehmet",
        createdAt: minutesAgo(8),
        updatedAt: minutesAgo(8),
        timeline: [{ at: minutesAgo(8), status: "giris-bekleniyor", note: "Online randevu. Giriş onayı yok; sayaç kapalı." }],
      }),
    ],
    appointments: [
      {
        id: "RDV-220",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        serviceId: "far-restorasyon",
        serviceName: "Far temizliği ve parlatma",
        date: today,
        time: "16:30",
        notes: "Akşam teslim.",
        status: "onaylandi",
        createdAt: minutesAgo(90),
      },
      {
        id: "RDV-221",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        serviceId: "ic-dis-yikama",
        serviceName: ic.name,
        date: today,
        time: "09:00",
        notes: "Demo takip kaydı.",
        status: "onaylandi",
        createdAt: minutesAgo(8),
      },
      {
        id: "RDV-218",
        customerId: "c-ayse",
        customerName: "Ayşe Kaya",
        phone: "05321220011",
        plate: "06 AYK 142",
        vehicle: "2019 Renault Megane",
        serviceId: "ic-dis-yikama",
        serviceName: ic.name,
        date: today,
        time: "10:30",
        notes: "",
        status: "bekliyor",
        createdAt: minutesAgo(120),
      },
    ],
    roadside: [
      {
        id: "YY-77",
        customerId: "c-oguz",
        customerName: "Oğuz Demir",
        phone: "05309876543",
        plate: "06 OGZ 330",
        vehicle: "2020 Ford Transit",
        location: "Dikmen Cad. üzerinde, belediye otobüs durağının 50 m gerisi, sağ şerit.",
        issue: "Arka sağ lastik tamamen indi, stepne var.",
        urgency: "yuksek",
        status: "yolda",
        technicianId: "t-burak",
        createdAt: minutesAgo(22),
        updatedAt: minutesAgo(9),
        timeline: [
          { at: minutesAgo(22), status: "alindi", note: "Talep alındı, konum notu kaydedildi." },
          { at: minutesAgo(18), status: "yonlendirildi", note: "Burak Yol atandı." },
          { at: minutesAgo(9), status: "yolda", note: "ETA ~18 dakika." },
        ],
      },
      {
        id: "YY-78",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        location: "AVM kat −2, C blok, 214 nolu park.",
        issue: "Kontak açılmıyor, farlar zayıf.",
        urgency: "kritik",
        status: "alindi",
        createdAt: minutesAgo(6),
        updatedAt: minutesAgo(6),
        timeline: [{ at: minutesAgo(6), status: "alindi", note: "Kritik öncelik — akü takviye talebi." }],
      },
    ],
    accessoryOrders: [
      {
        id: "AKS-12",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        accessoryId: ACCESSORIES[0].id,
        accessoryName: ACCESSORIES[0].name,
        qty: 1,
        total: ACCESSORIES[0].price,
        notes: "BMW 5.20i 2021.",
        status: "hazirlaniyor",
        createdAt: minutesAgo(50),
      },
    ],
    inbox: [
      {
        id: "INB-1",
        customerId: "c-demo",
        kind: "randevu",
        refId: "RDV-221",
        title: "İç + dış yıkama randevusu — 06 ELT 01",
        unread: true,
        createdAt: minutesAgo(8),
        messages: [
          {
            at: minutesAgo(8),
            from: "sistem",
            text: "Randevunuz alındı. Saat gelmesi süreci başlatmaz. Araç girişte onaylanınca sayaç ve bildirimler açılır.",
          },
        ],
      },
    ],
    notifications: [
      {
        id: "NT-1",
        title: "Giriş bekleniyor",
        body: "IS-1044 · Demo Müşteri tesiste, onay bekliyor.",
        href: "/yonetici/isler/IS-1044",
        at: minutesAgo(8),
        read: false,
      },
    ],
    whatsappOutbox: [],
    coupons: [
      {
        id: "cp-1",
        customerId: "c-demo",
        code: "ELIT20",
        title: "Seramik keşif %20",
        rule: "Keşif randevusunda geçerli",
        expires: "30 Eylül 2026",
        status: "aktif",
      },
    ],
    campaignNotif: true,
    couponNotif: true,
  };
}
