import { ACCESSORIES, SERVICES } from "./catalog";
import { minutesAgo, todayISO, uid } from "./format";
import type { AppState, Customer, Technician } from "./types";

const customers: Customer[] = [
  {
    id: "c-demo",
    name: "Demo Müşteri",
    phone: "05551234567",
    plate: "06 ELT 01",
    vehicle: "2021 Volkswagen Passat",
  },
  {
    id: "c-ayse",
    name: "Ayşe Kaya",
    phone: "05321220011",
    plate: "06 AYK 142",
    vehicle: "2019 Renault Megane",
  },
  {
    id: "c-cem",
    name: "Cem Yıldız",
    phone: "05423334455",
    plate: "06 CM 908",
    vehicle: "2022 Toyota Corolla",
  },
  {
    id: "c-burcu",
    name: "Burcu Şen",
    phone: "05076667788",
    plate: "06 BRC 77",
    vehicle: "2018 BMW 3.20",
  },
  {
    id: "c-oguz",
    name: "Oğuz Demir",
    phone: "05309876543",
    plate: "06 OGZ 330",
    vehicle: "2020 Ford Transit",
  },
];

const technicians: Technician[] = [
  { id: "t-mehmet", name: "Mehmet Usta", role: "Yıkama / kurutma", load: 3, shift: "08:30–17:00" },
  { id: "t-deniz", name: "Deniz Karaca", role: "Detailing", load: 2, shift: "09:00–18:00" },
  { id: "t-ali", name: "Ali Koç", role: "Lastik & balans", load: 2, shift: "08:30–18:30" },
  { id: "t-burak", name: "Burak Yol", role: "Yol yardım", load: 1, shift: "Sahada 24/7 nöbet" },
  { id: "t-elif", name: "Elif Aksoy", role: "Karşılama / kasa", load: 1, shift: "08:30–20:00" },
];

export function buildSeed(): AppState {
  const today = todayISO();
  const ic = SERVICES.find((s) => s.id === "ic-dis-yikama")!;
  const dis = SERVICES.find((s) => s.id === "dis-yikama")!;
  const det = SERVICES.find((s) => s.id === "detayli-ic")!;
  const lastik = SERVICES.find((s) => s.id === "lastik-degisim")!;

  return {
    session: { role: "guest", name: "Misafir" },
    customers,
    technicians,
    jobs: [
      {
        id: "IS-1042",
        kind: "yikama",
        customerId: "c-ayse",
        customerName: "Ayşe Kaya",
        phone: "05321220011",
        plate: "06 AYK 142",
        vehicle: "2019 Renault Megane",
        serviceId: ic.id,
        serviceName: ic.name,
        notes: "Çocuk koltuğu var, hayvan tüyü yok.",
        estimate: 650,
        status: "yikamada",
        technicianId: "t-mehmet",
        createdAt: minutesAgo(40),
        updatedAt: minutesAgo(12),
        timeline: [
          { at: minutesAgo(40), status: "kuyrukta", note: "Plaka okundu, kuyruğa alındı." },
          { at: minutesAgo(12), status: "yikamada", note: "Mehmet Usta başladı." },
        ],
      },
      {
        id: "IS-1043",
        kind: "yikama",
        customerId: "c-cem",
        customerName: "Cem Yıldız",
        phone: "05423334455",
        plate: "06 CM 908",
        vehicle: "2022 Toyota Corolla",
        serviceId: dis.id,
        serviceName: dis.name,
        notes: "Sadece dış, acelem var.",
        estimate: 350,
        status: "kuyrukta",
        technicianId: "t-mehmet",
        createdAt: minutesAgo(18),
        updatedAt: minutesAgo(18),
        timeline: [{ at: minutesAgo(18), status: "kuyrukta", note: "Walk-in kayıt." }],
      },
      {
        id: "IS-1038",
        kind: "detailing",
        customerId: "c-burcu",
        customerName: "Burcu Şen",
        phone: "05076667788",
        plate: "06 BRC 77",
        vehicle: "2018 BMW 3.20",
        serviceId: det.id,
        serviceName: det.name,
        notes: "Deri koltuk bakım kremi uygulansın.",
        estimate: 2200,
        status: "kurulama",
        technicianId: "t-deniz",
        createdAt: minutesAgo(180),
        updatedAt: minutesAgo(25),
        timeline: [
          { at: minutesAgo(180), status: "kuyrukta", note: "Randevulu giriş." },
          { at: minutesAgo(150), status: "yikamada", note: "İç detailing başladı." },
          { at: minutesAgo(25), status: "kurulama", note: "Kurutma ve kontrol." },
        ],
      },
      {
        id: "IS-1031",
        kind: "lastik",
        customerId: "c-oguz",
        customerName: "Oğuz Demir",
        phone: "05309876543",
        plate: "06 OGZ 330",
        vehicle: "2020 Ford Transit",
        serviceId: lastik.id,
        serviceName: lastik.name,
        notes: "Ön iki lastik 215/75 R16C.",
        estimate: 4800,
        status: "teslim",
        technicianId: "t-ali",
        createdAt: minutesAgo(240),
        updatedAt: minutesAgo(50),
        timeline: [
          { at: minutesAgo(240), status: "kuyrukta", note: "Lastikler kasadan çıktı." },
          { at: minutesAgo(200), status: "yikamada", note: "Sök-tak (montaj)." },
          { at: minutesAgo(80), status: "kurulama", note: "Balans ve tork." },
          { at: minutesAgo(50), status: "teslim", note: "Teslim ve tahsilat." },
        ],
      },
      {
        id: "IS-1044",
        kind: "yikama",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        serviceId: ic.id,
        serviceName: ic.name,
        notes: "Demo takip kaydı.",
        estimate: 650,
        status: "kuyrukta",
        technicianId: "t-mehmet",
        createdAt: minutesAgo(8),
        updatedAt: minutesAgo(8),
        timeline: [{ at: minutesAgo(8), status: "kuyrukta", note: "Online randevu ile kuyruğa alındı." }],
      },
    ],
    appointments: [
      {
        id: "RDV-220",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        serviceId: "far-restorasyon",
        serviceName: "Far temizliği ve parlatma",
        date: today,
        time: "16:30",
        notes: "Akşam teslim.",
        status: "onaylandi",
        createdAt: minutesAgo(90),
      },
      {
        id: "RDV-221",
        customerId: "c-ayse",
        customerName: "Ayşe Kaya",
        phone: "05321220011",
        plate: "06 AYK 142",
        vehicle: "2019 Renault Megane",
        serviceId: "rot-balans",
        serviceName: "Rot balans & rot ayarı talebi",
        date: today,
        time: "11:00",
        notes: "120 km/s üzeri titreşim.",
        status: "bekliyor",
        createdAt: minutesAgo(55),
      },
      {
        id: "RDV-218",
        customerId: "c-cem",
        customerName: "Cem Yıldız",
        phone: "05423334455",
        plate: "06 CM 908",
        vehicle: "2022 Toyota Corolla",
        serviceId: "dis-detailing",
        serviceName: "Dış detailing + pasta-cila",
        date: today,
        time: "14:00",
        notes: "Keşif sonrası pasta şiddeti.",
        status: "onaylandi",
        createdAt: minutesAgo(400),
      },
    ],
    roadside: [
      {
        id: "YY-77",
        customerId: "c-oguz",
        customerName: "Oğuz Demir",
        phone: "05309876543",
        plate: "06 OGZ 330",
        vehicle: "2020 Ford Transit",
        location: "Dikmen Cad. üzerinde, belediye otobüs durağının 50 m gerisi, sağ şerit.",
        issue: "Arka sağ lastik tamamen indi, stepne var.",
        urgency: "yuksek",
        status: "yolda",
        technicianId: "t-burak",
        createdAt: minutesAgo(22),
        updatedAt: minutesAgo(9),
        timeline: [
          { at: minutesAgo(22), status: "alindi", note: "Talep alındı, konum notu kaydedildi." },
          { at: minutesAgo(18), status: "yonlendirildi", note: "Burak Yol atandı." },
          { at: minutesAgo(9), status: "yolda", note: "ETA ~18 dakika." },
        ],
      },
      {
        id: "YY-78",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        plate: "06 ELT 01",
        vehicle: "2021 Volkswagen Passat",
        location: "AVM kat −2, C blok, 214 nolu park.",
        issue: "Kontak açılmıyor, farlar zayıf.",
        urgency: "kritik",
        status: "alindi",
        createdAt: minutesAgo(6),
        updatedAt: minutesAgo(6),
        timeline: [
          { at: minutesAgo(6), status: "alindi", note: "Kritik öncelik — akü takviye talebi." },
        ],
      },
    ],
    accessoryOrders: [
      {
        id: "AKS-12",
        customerId: "c-demo",
        customerName: "Demo Müşteri",
        phone: "05551234567",
        accessoryId: "acc-paspas",
        accessoryName: ACCESSORIES[0].name,
        qty: 1,
        total: 1850,
        notes: "Passat B8, siyah.",
        status: "hazirlaniyor",
        createdAt: minutesAgo(120),
      },
    ],
    inbox: [
      {
        id: uid("INB"),
        customerId: "c-demo",
        kind: "is",
        refId: "IS-1044",
        title: "İç + dış yıkama — 06 ELT 01",
        unread: true,
        createdAt: minutesAgo(8),
        messages: [
          {
            at: minutesAgo(8),
            from: "sistem",
            text: "Talebiniz kuyruğa alındı. Sıra geldiğinde durum ‘Yıkamada’ olarak güncellenir. Temsilci aramanıza gerek yok.",
          },
        ],
      },
      {
        id: uid("INB"),
        customerId: "c-demo",
        kind: "yol-yardim",
        refId: "YY-78",
        title: "Yol yardım — AVM kat −2",
        unread: true,
        createdAt: minutesAgo(6),
        messages: [
          {
            at: minutesAgo(6),
            from: "sistem",
            text: "Kritik yol yardım talebiniz alındı. En yakın ekip yönlendirilecek; ETA panoda görünecek.",
          },
        ],
      },
      {
        id: uid("INB"),
        customerId: "c-demo",
        kind: "aksesuar",
        refId: "AKS-12",
        title: "Paspas seti siparişi",
        unread: false,
        createdAt: minutesAgo(120),
        messages: [
          {
            at: minutesAgo(120),
            from: "sistem",
            text: "Siparişiniz hazırlanıyor. Stok teyidi sonrası ‘Teslime hazır’ mesajı gelecek.",
          },
        ],
      },
    ],
    notifications: [
      {
        id: uid("NT"),
        title: "Yeni yol yardım",
        body: "YY-78 · Demo Müşteri · kritik akü",
        href: "/panel/isler/YY-78",
        at: minutesAgo(6),
        read: false,
      },
      {
        id: uid("NT"),
        title: "Randevu onayı bekliyor",
        body: "RDV-221 · Ayşe Kaya · rot balans 11:00",
        href: "/panel",
        at: minutesAgo(55),
        read: false,
      },
      {
        id: uid("NT"),
        title: "Yıkama başladı",
        body: "IS-1042 · 06 AYK 142",
        href: "/panel/isler/IS-1042",
        at: minutesAgo(12),
        read: true,
      },
    ],
  };
}
